name: Build and Upload Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install wine and dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine64 wine32

    - name: Ensure build.sh has execute permissions
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x build.sh

    - name: Execute build.sh script
      run: |
        cd $GITHUB_WORKSPACE
        wine pyinstaller --onefile Escritorio/YouTubeDownloaderBPM/main.py


    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main_exe
        path: $GITHUB_WORKSPACE/Escritorio/YouTubeDownloaderBPM-Binaries/main.exe
