name: Build and Deploy

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Reemplaza '3.x' con la versión de Python que necesitas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build script
      run: ./build.sh

    - name: Clone Binaries Repository
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git clone https://$PAT@github.com/Juanan242/YouTubeDownloaderBPM-Binaries-Linux.git binaries-repo
        rm -rf binaries-repo/*  # Optional: clean the binaries repo before copying new files

    - name: Move generated files to binaries repository
      run: |
        mv dist/* binaries-repo/

    - name: Commit and push changes to binaries repository
      working-directory: binaries-repo
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add generated binaries"
        git push

