name: Build and Upload Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and upload executable
        run: $GITHUB_WORKSPACE/Escritorio/YouTubeDownloaderBPM/build.sh
