name: Build and Upload Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute build.sh script
      run: |
        cd $GITHUB_WORKSPACE
        ./build.sh

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main_exe
        path: $GITHUB_WORKSPACE/Escritorio/YouTubeDownloaderBPM-Binaries/main.exe
