name: Build and Upload Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install pyinstaller

    - name: Ensure build.sh has execute permissions
      run: chmod +x build.sh

    - name: Execute build.sh script
      run: ./build.sh 

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main_exe
        path: $GITHUB_WORKSPACE/YouTubeDownloaderBPM-Binaries/
