name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build executable
      run: |
        cd $GITHUB_WORKSPACE
        wine pyinstaller --onefile main.py

    - name: Move executable to binaries directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/Escritorio/YouTubeDownloaderBPM-Binaries
        mv dist/main.exe $GITHUB_WORKSPACE/Escritorio/YouTubeDownloaderBPM-Binaries/

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main_exe
        path: $GITHUB_WORKSPACE/Escritorio/YouTubeDownloaderBPM-Binaries/main.exe
